// state.js — single exported state object with all mutable globals

export const state = {
  currentCharacter: null,
  currentHistoryId: null,
  selectedDetail: 'medium',
  forgeRolledStats: null,
  currentItem: null,
  currentItemHistoryId: null,
  currentShop: null,
  currentShopHistoryId: null,
  currentShopSynced: false,
  currentShopDocmostUrl: null,
  shopSelectedRarities: new Set(['Common', 'Uncommon']),
  shopDetailLevel: 'medium',
  currentFaction: null,
  currentFactionHistoryId: null,
  currentFactionSynced: false,
  currentFactionDocmostUrl: null,
  currentMonster: null,
  currentMonsterHistoryId: null,
  currentMonsterSynced: false,
  currentMonsterDocmostUrl: null,
  historyEntries: [],
  selectedHistoryEntryId: null,
  selectedHistoryEntryType: null,
  historyActiveTag: null,
  currentPlayerCharacter: null,
  currentPlayerCharacterId: null,
  partyEntries: [],
  selectedPcMode: 'generate',
  pcRolledStats: null,
  _modalMode: null,
  _modalGeneratedItem: null,
  _modalGeneratedItemHistoryId: null,
  _modalGeneratedChar: null,
  _modalGeneratedCharHistoryId: null,
  _modalFactionContext: null,
  _modalShopContext: null,
  // Validation limits — loaded from /api/settings, kept in sync with backend
  limits: {
    max_concept_length: 1000,
    max_notes_length: 500,
    max_character_level: 20,
    max_shop_items: 20,
  },
  currentLocation: null,
  currentLocationHistoryId: null,
  currentLocationSynced: false,
  currentLocationDocmostUrl: null,
  currentLocationParent: null,
  currentLocationChildren: [],
  locationDetailLevel: 'medium',
};

// Expose for utils.js context picker (avoids circular ES module import)
window._state = state;
